import "./globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Navigation from "@/ui/Navigation";
import Sidebar from "@/ui/Sidebar";

const vazirmatn = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={vazirmatn.className}>
        <Navigation />

        <main className="m-auto lg:px-10 px-5 w-full min-h-screenHeight max-w-screen-2xl mt-10 grid grid-cols-11">
          <Sidebar />

          <main
            className="remove-scrollbar col-span-8 lg:col-span-9 min-h-[10rem] h-screen overflow-y-auto"
            data-testid="main-element"
          >
            {children}
          </main>
        </main>
      </body>
    </html>
  );
}
